### PR TITLE
corrected order in schema

### PR DESCRIPTION
**Pull request by gnanaprakash-ravi**
This PR is for the issue [709](https://github.com/zinggAI/zingg/issues/709)

### CODE REVIEW

**Comment by vikasgupta78** [comment]
What all testing have you done? And are these the only 2 configs?

**Comment by vikasgupta78** [comment]
Also is there an impact on FebrlExample.py

**Comment by vikasgupta78** [comment]
When I say impact on FebrlExample.py I mean order needs to be same in both as both use test.csv

**Comment by gnanaprakash-ravi** [comment]
Yes FebrlExample.py also, areacode was after the state, and i changed it, i will run the 4 phases on config.json and FebrlExample.py testing!!

**Comment by vikasgupta78** [comment]
@gnanaprakash-ravi after the merge of PR for det match changes , you might want to revisit this as this may give conflict in merge

**Pull request closed without merging**
