### PR TITLE
Introduced new phase findLabel

### PR DESCRIPTION
**Pull request by navinrathore**
#146

### CODE REVIEW

**Comment by navinrathore** [comment]
In zingg HELP()  - some of the recently added phases is not present. is that required?
ZinggOption has been set as "FIND_LABEL" in FindLabeller.java?

**Comment by sonalgoyal** [comment]
rename to findAndLabel

**Comment by sonalgoyal** [comment]
add to help whatever is missing

**Comment by sonalgoyal** [comment]
move documenation to after label - say explicitly that this is good for small datasets else if your findTrainingData takes a long time, the user will have to wait for the console for labelling.

**Comment by navinrathore** [comment]
**Help component:**  
There is no need to add anything. the below line include all the phases.
--phase:		train|match|trainMatch|findTrainingData|label|link|generateDocs|updateLabel|findAndLabel
**Rename findAndLabel:**
renamed to findAndLabel  
**Documentation:**
moved the page after label. Added content on the page.

**Pull request merged**
