### PR TITLE
Display how many pairs've been labelled matches and non matches #87

### PR DESCRIPTION
**Pull request by navinrathore**
During the Labeling phase, track the number of pairs that has been marked match and non match. Display same to the user on cli.

### CODE REVIEW

**Review by sonalgoyal — CHANGES_REQUESTED** [review]
as discussed, cant say stats have to be there. stats have to be overall, not just existing round

**Comment by navinrathore** [comment]
Consolidated stats are printed

**Comment by sonalgoyal** [comment]
> as discussed, cant say stats have to be there. stats have to be overall, not just existing round

does this change have cant say stats as commented on previously?

**Review by sonalgoyal — CHANGES_REQUESTED** [review]
i dont see cant say stats?

**Comment by navinrathore** [comment]
Not Sure has been added

**Pull request merged**
