### PR TITLE
Block and stop word test

### PR DESCRIPTION
**Pull request by Nitish1814**
Block and StopWord Tests

### CODE REVIEW

**Comment by vikasgupta78** [comment]
as discussed I am not convinced that we need IWithSession and WithSession in the main code. Also naming needs to be fixed. Do an impact analysis and discuss with @sonalgoyal

**Comment by vikasgupta78** [comment]
there was already a class TestBlock in zingg spark core? Why is that not being reused?

**Comment by vikasgupta78** [comment]
there was existing TestStopWords class why it has been deleted instead of renamed / moved to maintain history

**Comment by Nitish1814** [comment]
> there was already a class TestBlock in zingg spark core? Why is that not being reused?

just restructured package, reused same file only !

**Comment by Nitish1814** [comment]
> there was existing TestStopWords class why it has been deleted instead of renamed / moved to maintain history

1: TestStopWords first made generic
2: Renamed to TestStopWordsBase
3: Moved to common

**Comment by Nitish1814** [comment]
> there was already a class TestBlock in zingg spark core? Why is that not being reused?

1: TestBlock first made generic
2: Renamed to TestBlockBase
3: Moved to common

**Comment by Nitish1814** [comment]
> PojoToArrayConverter

removed

**Pull request closed without merging**
