### PR TITLE
Fixed broken link and added favicon.ico

### PR DESCRIPTION
**Pull request by navinrathore**
The febrl directory link still to be worked upon. At web server label it may be controlled.

### CODE REVIEW

**Review by sonalgoyal — CHANGES_REQUESTED** [review]
can you please also make the changes to the folders and hardware sizing as per #57 so that we can merge this ?

**Comment by sonalgoyal** [comment]
Read more about Zingg Pipes for datastore connections here.  - pipes link broken at https://docs.zingg.ai/docs/setup/configuration.html

**Comment by navinrathore** [comment]
Two new PRs for issues. This will be deleted.

**Comment by navinrathore** [comment]
commits of this PR have been merged through two different PRs (#61, #62). Hence, closing this.

**Pull request closed without merging**
